# -*- coding: utf-8 -*-
"""RAG Pipeline for Legal Document Question Answer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6jNwUqL0YbnuQKGgFM-NdOTaa9GgXxE
"""

"""
RAG Pipeline for Legal Document Question Answering

This script:
1. Loads and preprocesses legal documents
2. Creates embeddings and a vector database
3. Builds a RAG chain
4. Evaluates results using ROUGE, BLEU, and RAGAS

Environment variable required:
OPENAI_API_KEY=<your_api_key>
"""

# =========================
# Imports
# =========================
import os
import re
import json
import logging
import random
from pathlib import Path
from typing import List, Dict

import pandas as pd
import nltk
from collections import Counter

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge_score import rouge_scorer

from datasets import Dataset
from ragas import evaluate
from ragas.metrics import faithfulness, answer_relevancy
from ragas.embeddings import OpenAIEmbeddings as RagasOpenAIEmbeddings
from openai import OpenAI

# =========================
# Environment Setup
# =========================
if not os.getenv("OPENAI_API_KEY"):
    raise EnvironmentError("Please set OPENAI_API_KEY as an environment variable.")

nltk.download("punkt")
nltk.download("stopwords")

# =========================
# Configuration
# =========================
BASE_PATH = "data"  # Put your dataset inside a 'data' folder
VECTOR_DB_DIR = "vector_db"

DATASET_FOLDERS = {
    "contractnli": os.path.join(BASE_PATH, "contractnli"),
    "cuad": os.path.join(BASE_PATH, "cuad"),
    "maud": os.path.join(BASE_PATH, "maud"),
    "privacy_qa": os.path.join(BASE_PATH, "privacy_qa"),
}

STOP_WORDS = set(nltk.corpus.stopwords.words("english"))

logging.basicConfig(
    filename="preprocessing_errors.log",
    level=logging.WARNING,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

# =========================
# Text Cleaning
# =========================
def preprocess_text(text: str) -> str:
    text = text.lower()
    text = re.sub(r'\b[\w\.-]+@[\w\.-]+\.\w+\b', ' ', text)
    text = re.sub(r'\b\d{10}\b|\+\d{1,3}[-\s]?\d{7,10}', ' ', text)
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    tokens = [w for w in text.split() if w not in STOP_WORDS]
    return " ".join(tokens)

# =========================
# Load Documents
# =========================
def load_documents(dataset_folders: Dict[str, str]) -> List[Dict]:
    documents = []

    for dataset, folder_path in dataset_folders.items():
        for root, _, files in os.walk(folder_path):
            for file in files:
                if file.endswith(".txt"):
                    file_path = os.path.join(root, file)

                    try:
                        with open(file_path, "r", encoding="utf-8") as f:
                            raw_text = f.read()

                        if not raw_text.strip():
                            continue

                        processed = preprocess_text(raw_text)

                        documents.append({
                            "dataset": dataset,
                            "file_name": file,
                            "file_path": file_path,
                            "text": processed,
                            "length": len(processed.split())
                        })

                    except Exception as e:
                        logging.warning(f"Skipping file {file_path}: {e}")

    return documents

# =========================
# Chunk Documents
# =========================
def create_chunks(documents: List[Dict]) -> List[Document]:
    langchain_docs = [
        Document(
            page_content=doc["text"],
            metadata={
                "dataset": doc["dataset"],
                "file_name": doc["file_name"],
                "file_path": doc["file_path"]
            }
        )
        for doc in documents
    ]

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50
    )

    return splitter.split_documents(langchain_docs)

# =========================
# Create Vector DB
# =========================
def build_vector_db(chunks: List[Document]):
    embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

    vector_db = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        persist_directory=VECTOR_DB_DIR
    )

    vector_db.persist()
    return vector_db

# =========================
# Build RAG Chain
# =========================
def create_rag_chain(vector_db):
    retriever = vector_db.as_retriever(search_kwargs={"k": 5})

    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0
    )

    prompt = ChatPromptTemplate.from_template(
        """
You are a legal assistant.
Answer strictly using the provided context.
If not found, say: "Answer not found in the document."

Context:
{context}

Question:
{question}

Answer:
"""
    )

    chain = (
        {
            "context": retriever,
            "question": RunnablePassthrough()
        }
        | prompt
        | llm
        | StrOutputParser()
    )

    return chain, retriever

# =========================
# Generate Answer
# =========================
def generate_answer(question, chain, retriever):
    answer = chain.invoke(question)
    sources = retriever.invoke(question)
    return answer, sources

# =========================
# Evaluation
# =========================
def evaluate_pipeline(questions, ground_truths, chain, retriever, max_q=10):
    rouge_scores = []
    bleu_scores = []
    predictions = []
    contexts = []

    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)
    smoothie = SmoothingFunction().method4

    for i in range(min(max_q, len(questions))):
        pred, retrieved_docs = generate_answer(questions[i], chain, retriever)

        gt = ground_truths[i]
        predictions.append(pred)

        rouge = scorer.score(gt, pred)['rougeL'].fmeasure
        rouge_scores.append(rouge)

        bleu = sentence_bleu(
            [nltk.word_tokenize(gt)],
            nltk.word_tokenize(pred),
            smoothing_function=smoothie
        )
        bleu_scores.append(bleu)

        contexts.append([doc.page_content for doc in retrieved_docs])

    dataset = Dataset.from_dict({
        "question": questions[:len(predictions)],
        "answer": predictions,
        "ground_truth": ground_truths[:len(predictions)],
        "contexts": contexts
    })

    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    ragas_embeddings = RagasOpenAIEmbeddings(
        client=client,
        model="text-embedding-3-small"
    )

    ragas_result = evaluate(
        dataset=dataset,
        metrics=[faithfulness, answer_relevancy],
        embeddings=ragas_embeddings
    )

    return {
        "avg_rougeL": sum(rouge_scores) / len(rouge_scores),
        "avg_bleu": sum(bleu_scores) / len(bleu_scores),
        "ragas": ragas_result
    }

# =========================
# Main Execution
# =========================
if __name__ == "__main__":
    print("Loading documents...")
    docs = load_documents(DATASET_FOLDERS)

    print("Creating chunks...")
    chunks = create_chunks(docs)

    print("Building vector database...")
    vector_db = build_vector_db(chunks)

    print("Creating RAG chain...")
    rag_chain, retriever = create_rag_chain(vector_db)

    sample_question = "Does the agreement grant rights to confidential information?"
    answer, sources = generate_answer(sample_question, rag_chain, retriever)

    print("\nAnswer:\n", answer)
    print("\nSources:")
    for s in sources:
        print("-", s.metadata.get("file_name"))